version: '3.8'

services:
  backend:
    build:
      context: ./hireready-backend
      dockerfile: Dockerfile
    volumes:
      - ./hireready-backend/.env:/app/.env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./hireready-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

networks:
  default:
    name: hireready-network
